/**
 * Regenerates docs/model-inventory.md and huggingface/manifests/models.json
 * from site/src/data/models.ts — the single source of truth.
 *
 *   cd site && npx tsx ../scripts/generate-docs.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { models, sortedModels, repoName, hfUrl, statusLabel, counts, newId, HF_ORG } from "../site/src/data/models";
import { paperNotation, corpusPhrase, stageShort } from "../site/src/data/naming";
import { project } from "../site/src/data/project";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const write = (rel: string, body: string) => {
  const p = join(ROOT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, body);
  console.log("wrote", rel);
};

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const dash = "—";

/* ────────────────────────── model-inventory.md ────────────────────────── */

const row = (m: (typeof models)[number]) => {
  const nid = newId(m.hf_id);
  const repoCell = nid
    ? `[\`${repoName(nid)}\`](${hfUrl(nid)})<br><sub>was [\`${repoName(m.hf_id)}\`](${hfUrl(m.hf_id)})</sub>`
    : `[\`${repoName(m.hf_id)}\`](${hfUrl(m.hf_id)})`;
  return [
    repoCell,
    m.canonical_corpora.length ? paperNotation(m.canonical_corpora) : "Unverified",
    `${stageShort[m.stage]} (\`${m.legacy_stage}\`)`,
    m.merge_method ?? m.synthetic_generator ?? dash,
    m.paper_variant ?? "No",
    m.status === "recommended" ? "**Yes**" : "No",
    m.status === "legacy" || m.status === "superseded" ? "Yes" : "No",
    m.superseded_by ? `\`${repoName(m.superseded_by)}\`` : m.duplicate_of ? `duplicate of \`${repoName(m.duplicate_of)}\`` : dash,
    esc(m.notes),
  ].map((c) => c.replace(/\|/g, "\\|")).join(" | ").replace(/^/, "| ") + " |";
};

const section = (title: string, blurb: string, list: typeof models) => `
### ${title}

${blurb}

| HF repository | Canonical corpora | Stage | Generator / merge | Paper model? | Recommended? | Legacy? | Superseded by | Notes |
|---|---|---|---|---|---|---|---|---|
${list.map(row).join("\n")}
`;

const byStatus = (...s: string[]) => sortedModels.filter((m) => s.includes(m.status));

const inventory = `<!-- GENERATED by scripts/generate-docs.ts from site/src/data/models.ts. Do not edit by hand. -->

# Model inventory

Every ClimateModernBERT checkpoint published under the [\`sraj\`](${project.links.hfOrg})
Hugging Face account, with its mapping to the manuscript's corpus notation.

Read [model-naming.md](./model-naming.md) first — it explains why the repository names
look nothing like the paper's notation, and how the mapping was established.

- **${models.filter((m) => newId(m.hf_id)).length}** republished under
  [\`${HF_ORG}\`](https://huggingface.co/${HF_ORG}) with names matching the paper's notation;
  the originals under \`sraj/*\` are untouched
- **${counts.total}** checkpoints catalogued in total
- **${counts.merged}** parameter-space merges, **${counts.total - counts.merged}** jointly trained
- **${counts.ambiguous}** carry an unresolved mapping and are marked *Unverified* or flagged in the notes
- **${counts.superseded}** are superseded or byte-identical duplicates. **Nothing has been deleted from the Hub.**

## How mappings were established

Three kinds of evidence, in decreasing strength:

1. **\`mergekit\`** — the repository's own \`mergekit_config.yml\` names its component
   checkpoints exactly. This is how θ<sub>Soup</sub> and the drop-one ablations were
   pinned down, and it is the only mechanical evidence available.
2. **\`collection\`** — membership in the curated
   [ClimateModernBERT collection](${project.links.hfCollection}), described by its author as
   "Final Models from the paper".
3. **\`name\`** — inference from the historical repository name alone. Weakest; a name is
   not proof (see the MARK/ZYDA rule in model-naming.md).

Where two kinds of evidence disagree, the entry is flagged rather than silently resolved.

## Not in this table

The \`sraj\` account also hosts models from unrelated projects — Llama and OLMo
fine-tunes, \`narrascore\`, and \`ModernBERT_Squad*\`. Several \`MB_CPT_*\`, \`MB_CX*\`
and \`MB_PT_*\` repositories from October–November 2025 predate the ClimateModernBERT
naming scheme entirely and cannot be mapped to a manuscript configuration; they are
excluded rather than guessed at.

${section(
  "Recommended and paper models",
  "Configurations that correspond to a result reported in the manuscript.",
  byStatus("recommended", "paper"),
)}
${section(
  "Experimental checkpoints",
  "Released, but with no reported result in the manuscript. Useful for follow-up work; not part of the paper's claims.",
  byStatus("experimental"),
)}
${section(
  "Legacy and superseded checkpoints",
  "Earlier pipeline stages, retained for provenance. Excluded from the primary website catalog but fully linked. Nothing here has been removed from the Hub.",
  byStatus("legacy", "superseded"),
)}
## Not released

Two Phase-1 configurations reported in Table 2 of the manuscript have no matching
public checkpoint:

| Paper configuration | Expected repository name | Status |
|---|---|---|
| ${paperNotation(["S", "F"])} Phase 1 | \`CMB_FWEdu_V2_FastTxt_SYN_CX\` | Not found on the Hub |
| ${paperNotation(["A", "S", "F"])} Phase 1 | \`CMB_FWEdu_V2_FastTxt_MARK_SYN_CX\` | Not found on the Hub |

Their Phase-2 counterparts are both published.
`;

write("docs/model-inventory.md", inventory);

/* ─────────────────────── huggingface/manifests/models.json ─────────────────────── */

const manifest = {
  $comment:
    "GENERATED by scripts/generate-docs.ts from site/src/data/models.ts. Do not edit by hand.",
  project: project.name,
  paper: { title: project.paperTitle, status: project.status, published: false },
  generated_from: "site/src/data/models.ts",
  corpora: {
    A: { name: "Academic", tokens: "~1.28B", docs: "~5M" },
    F: { name: "Climate Web", tokens: "~5B", docs: "2.59M" },
    S: { name: "Synthetic", tokens: "~0.14B", docs: "~20K" },
  },
  stages: {
    phase1: { label: "Phase 1 · Continued Pretraining", legacy_suffix: "CX" },
    phase2: { label: "Phase 2 · LRD Specialization", legacy_suffix: "CX_LRD" },
  },
  counts,
  organization: HF_ORG,
  models: models.map((m) => ({
    hf_id: m.hf_id,
    hf_url: hfUrl(m.hf_id),
    // Republished name inside HF_ORG, or null when the checkpoint stays only
    // under sraj/*. Consumed by scripts/migrate_to_org.py.
    new_id: newId(m.hf_id),
    new_url: newId(m.hf_id) ? hfUrl(newId(m.hf_id)!) : null,
    display_name: m.display_name,
    canonical_corpora: m.canonical_corpora,
    academic: m.canonical_corpora.includes("A"),
    web: m.canonical_corpora.includes("F"),
    synthetic: m.canonical_corpora.includes("S"),
    corpus_phrase: m.canonical_corpora.length ? corpusPhrase(m.canonical_corpora) : null,
    paper_notation: m.canonical_corpora.length ? paperNotation(m.canonical_corpora) : null,
    stage: m.stage,
    legacy_stage: m.legacy_stage,
    family: m.family,
    status: m.status,
    status_label: statusLabel[m.status],
    paper_variant: m.paper_variant,
    avg_f1: m.avg_f1,
    merge_method: m.merge_method ?? null,
    merge_components: m.merge_components ?? null,
    merge_components_new: m.merge_components
      ? m.merge_components.map((c) => newId(c) ?? c)
      : null,
    synthetic_generator: m.synthetic_generator ?? null,
    superseded_by: m.superseded_by ?? null,
    duplicate_of: m.duplicate_of ?? null,
    evidence: m.evidence,
    ambiguous: !!m.ambiguous,
    notes: m.notes,
  })),
};

write("huggingface/manifests/models.json", JSON.stringify(manifest, null, 2) + "\n");
